name             'bootstrap_windows'
maintainer       'Levi Smith'
maintainer_email 'levi@fynx.me'
license          'MIT'
description      'Installs/Configures Windows Workstation'
version          '0.1.0'

supports 'windows'
depends 'windows', '~> 1.37'
depends 'chocolatey', '~> 0.4'
